title: SportIQ Pro
description: Sports performance and coaching science
theme: minima
baseurl: "/sportiqpro"
url: "https://siavashsed.github.io"
markdown: kramdown
permalink: /:year/:month/:day/:title/
show_excerpts: true
minima:
  skin: dark
